### PR TITLE
Handle saved Windows paths on Unix

### PR DESCRIPTION
**Pull request by paulfd**

### CODE REVIEW

**Review by redtide — COMMENTED** [review]
Maybe the solution is a "create and upload artifacts only when tagging a release or on pull requests, to keep the builds as minimum and fast as possible when just pushing a commit"

Also as self reminder we can omit the `${{` in `if` conditionals as stated in the [docs](https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions):

> [...] you may omit the `${{ }}` expression syntax because GitHub Actions automatically evaluates the `if` conditional as an expression [...]
You must use the `${{ }}` expression syntax or escape with `''`, `""`, or `()` when the expression starts with `!`, since `!` is reserved notation in YAML format.
Using the `${{ }}` expression syntax turns the contents into a string, and strings are truthy. For example, `if: true && ${{ false }}` will evaluate to true.

so these may be
`if: github.ref_type == 'tag' || github.event_name == 'pull_request'`

**Comment by atsushieno** [comment]
Assuming it is a fix for #95, I created another fix locally (noticed this one only after I creaeted mine) which is to replace `\` with `/` only on Windows. 

If this fix is going to be good and applied it's great, but note that `\` is a valid filename character on various Linux filesystems) so you cannot simply replace `\` without detecting the platform anyways.

Also, there are paths like "\\server\mypc\sfz\foobar.sfz" on Windows, so `path[1]` is not always `:`. Maybe `fs::path::is_absolute()` is good enough?

**Comment by redtide** [comment]
@paulfd what is the status? Should this be closed and merge #101 instead, adding the "create artifacts also on PR" feature on it?

**Comment by redtide** [comment]
Closing, #101 merged instead.

**Pull request closed without merging**
