### PR TITLE
Fix #95: replace `\` with `/` on Windows when saving file paths.

### LINKED ISSUE #95: Unable to send project from Windows user to Linux user
I seem to be running into an issue trying to send a project from a Windows user to a Linux user. The "User SFZ folder" is set correctly on both systems, and I can send projects from Linux to Windows with no issues whatsoever. However, when trying to send a project from Windows to Linux, the Linux user gets the full Windows style path of the soundfont in the soundfont selection region:

Whereas I would expect simply the name of the file to show up like so (this is what happens when I send a project from Linux to Windows and it works perfectly!)

Generally speaking I would expect users from all operating systems to be able to share projects without issue (as long as the "User SFZ folder" is set correctly of course!)
sfizz 1.2.1, DAW is reaper.

Linux version is Debian 12, Windows version is Windows 7 (apologies, that is what the user is using unfortunately).

If there are test builds for a bugfix, I am happy to test on my Linux system + Windows 7 vm.

### PR DESCRIPTION
**Pull request by atsushieno**
... and do vice versa on restore.

This is an alternative fix for #95 to  #100 (so if we apply #100 this fix is going to be unnecessary).

I haven't tested it on Windows yet, so I'm going to ask someone on Discord.

### CODE REVIEW

**Comment by paulfd** [comment]
I was afraid of going this route because I feared it would break session restores between versions, but it looks like it might be fine. I can give it a try later this week if you want.

**Comment by paulfd** [comment]
I took the liberty of pushing a couple fixes (one of which was a Trie build mistake on windows where it would forget the drive root). I'll try the Windows -> Unix path now.

**Comment by paulfd** [comment]
So it does seem to work out but you need to resave the projects for the transfer to work. OTOH, these projects did not properly transfer before so it's not like anything's lost.

In the end, it's probably a more elegant solution. I'll pull in the packages commit in this branch for testing.

**Comment by atsushieno** [comment]
Sorry, late reply here. I definitely do not want to have it breaking old data for newer versions. But having state from newer versions unable to load on older version would be alright IMO.

**Pull request merged**
